### ISSUE TITLE
Unable to set content size

### ISSUE THREAD

**Issue by anthonyjchriste** [10XGenomics/lz4-rs#24]
Currently, the ability to set the content size of the uncompressed data is not supported by this library, but it is supported in the C library: https://github.com/lz4/lz4/blob/d44371841a2f1728a3f36839fd4b7e872d0927d3/lib/lz4frame.h#L180

I've submitted a PR (https://github.com/10XGenomics/lz4-rs/pull/23) that exposes this functionality through lz4-sys and the lz4 Encoder struct. 

I would like to work with you to get this PR accepted. If you have the time, could you please review the PR and let me know if anything needs to be changed or addressed?

Really appreciate you taking over this project and appreciate your (and others) hard work.

**Comment by pmarks** [comment]
Fixed in #44
