### ISSUE TITLE
Decompressed data does not match original

### ISSUE THREAD

**Issue by michael-disalvo3** [10XGenomics/lz4-rs#41]
I wrote this program here: 
`use std::io::{self, Write, Read};

fn main() {

    // encode to a vec
    let mut enc = lz4::EncoderBuilder::new().build(Vec::new()).unwrap();

    // build our expected
    let mut expected = vec![0; 65536];

    // write 65530 bytes to our encoder and populate expected with same bytes
    for i in 0..65530 {
        enc.write(&[(i % 128) as u8; 1]).unwrap();
        expected[i] = (i % 128) as u8;
    }

    // finish the encoder and check for error
    let (v, r) = enc.finish();
    r.unwrap();

    // builder decoder around returned vec
    let mut dec = lz4::Decoder::new(&v[..]).unwrap();

    // compare decoded bytes to expected bytes
    let mut got = vec![0; 65536];
    dec.read_exact(&mut got[..]);
    assert_eq!(expected, got);
}`

It would be my expectation that the assert_eq!() call would come back as true, but panics due to `expected` and `got` not being equal. This program works when using other lz4 libraries. Am I misunderstanding what finish() is supposed to do, or is this a bug?

**Comment by niklasf** [comment]
The issue becomes apparent if you handle the result of:

```
dec.read_exact(&mut got[..]) // Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }
```

Only 65530 bytes were written to the encoder, but you're attempting to read into a slice of 65536 bytes.

**Comment by pmarks** [comment]
Yeah seems like either you read too many bytes, or what you do read will be 65530 bytes, which is not equal to the 65536 bytes you're expected.  Please re-open if you disagree.
