### ISSUE TITLE
lz4-sys 1.11.0 breaks tradition of aligning the version with lz4 – is this intentional?

### ISSUE THREAD

**Issue by musicinmybrain** [10XGenomics/lz4-rs#50]
As far as I can tell, the version of the `lz4-sys` crate has historically always been the same as the version of the `lz4` C library included in the published crate. With `lz4-sys` 1.11.0, which still contains `lz4` 1.10.0, these versions have diverged. Was this intentional? Is this what we should expect going forward – that these two version numbers will now be independent of each other?

**Comment by pmarks** [comment]
@musicinmybrain ugh my bad, thanks for catching. #49 introduced some changes to `lz4-sys` for WASM support, but did not change the actual lz4 version, so I should have called it `1.10.1`.   I could re-publish lz4-sys as `1.10.1`, and yank `1.11.0`, then make a minor revision of the main crate to point at `1.10.1` - does that sound right to you?

**Comment by musicinmybrain** [comment]
Perhaps you could take the opportunity to free the `lz4-sys` crate from synchronized versioning, and let it continue to diverge according to its own needs. You could instead use the [`BuildMetadata`](https://docs.rs/semver/latest/semver/struct.BuildMetadata.html) version field to indicate the wrapped `lz4` version, like one of the following:

- `1.11.1+1.10.0`
- `1.11.1+lz4-1.10.0`
- `1.11.1+liblz4-1.10.0`

This seems to be a common approach in other `-sys` crates.

If you release 1.10.1, then I think you’ll be in a bind again if `lz4` upstream issues a 1.10.1 patch-release.

**Comment by pmarks** [comment]
I do like that style, but interestingly cargo now gives this warning:
```% cargo check
warning: version requirement `1.11.1+lz4-1.10.0` for dependency `lz4-sys` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion```

But I will go ahead with this style, because i think it is important to communicate the lz4 version.
